version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    allow:
      - dependency-name: "@beland/*"
      - dependency-name: "beland-*"
    versioning-strategy: increase
